### ISSUE TITLE
无法导入文件夹

### ISSUE THREAD

**Issue by snylonue** [chanshiyucx/eriri#3]
win10 1909
加载动画后无反应

**Comment by zhangheng0027** [comment]
同上

**Comment by zhangheng0027** [comment]
> win10 1909
> 加载动画后无反应

多试几次后发现导入成功，应该要到上级目录，目录结构：D:/A/B/C/a.png, 正常操作是直接导入文件C，然后不成功，需要导入文件C的上级目录，然后文件C会当作漫画名展示

**Comment by snylonue** [comment]
@zhangheng0027 感谢
